version: "3"

services:
  botpress:
    image: botpress/server:v12_30_8
    restart: always
    ports: 
      - 3000:3000
  nginx:
    image: nginx:1.23.1-alpine
    restart: always
    depends_on:
      - botpress
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
